spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vehicle
    username: root
    password: asidsdamad1
  profiles:
    active: dev

cache:
  specs:
    redis:
      host: localhost
      port: 6379
      default-ttl: 15